// <auto-generated />
using System;
using AdminPanelEticaret.Models.Siniflar;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminPanelEticaret.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdminPanelEticaret.Models.Siniflar.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR");

                    b.HasKey("AdminId");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("AdminPanelEticaret.Models.Siniflar.Kategori", b =>
                {
                    b.Property<int>("KategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriID"));

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.HasKey("KategoriID");

                    b.ToTable("kategoris");
                });

            modelBuilder.Entity("AdminPanelEticaret.Models.Siniflar.Musteri", b =>
                {
                    b.Property<int>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriId"));

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("MusteriAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("MusteriMail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("MusteriSehir")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("MusteriSifre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("MusteriSoyadi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("MusteriTelNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR");

                    b.HasKey("MusteriId");

                    b.ToTable("musteris");
                });

            modelBuilder.Entity("AdminPanelEticaret.Models.Siniflar.Satislar", b =>
                {
                    b.Property<int>("SatisHareketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SatisHareketId"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("SatisHareketId");

                    b.HasIndex("MusteriId");

                    b.HasIndex("UrunId");

                    b.ToTable("satislars");
                });

            modelBuilder.Entity("AdminPanelEticaret.Models.Siniflar.Urun", b =>
                {
                    b.Property<int>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrunId"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<decimal?>("IndirimliFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KategoriID")
                        .HasColumnType("int");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("UrunGorsel")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("UrunMarka")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.Property<decimal>("UrunSatisFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<short>("UrunStok")
                        .HasColumnType("smallint");

                    b.Property<bool>("UrunStokDurum")
                        .HasColumnType("bit");

                    b.Property<string>("UrunYazar")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.HasKey("UrunId");

                    b.HasIndex("KategoriID");

                    b.ToTable("uruns");
                });

            modelBuilder.Entity("AdminPanelEticaret.Models.Siniflar.Satislar", b =>
                {
                    b.HasOne("AdminPanelEticaret.Models.Siniflar.Musteri", "Musteri")
                        .WithMany("satislars")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminPanelEticaret.Models.Siniflar.Urun", "Urun")
                        .WithMany("satislars")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("AdminPanelEticaret.Models.Siniflar.Urun", b =>
                {
                    b.HasOne("AdminPanelEticaret.Models.Siniflar.Kategori", "Kategori")
                        .WithMany("uruns")
                        .HasForeignKey("KategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("AdminPanelEticaret.Models.Siniflar.Kategori", b =>
                {
                    b.Navigation("uruns");
                });

            modelBuilder.Entity("AdminPanelEticaret.Models.Siniflar.Musteri", b =>
                {
                    b.Navigation("satislars");
                });

            modelBuilder.Entity("AdminPanelEticaret.Models.Siniflar.Urun", b =>
                {
                    b.Navigation("satislars");
                });
#pragma warning restore 612, 618
        }
    }
}
