// <auto-generated />
using System;
using ECommerceBackEnd.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceBackEnd.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251130183359_AdresSatisBaglantisiKuruldu")]
    partial class AdresSatisBaglantisiKuruldu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerceBackEnd.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR");

                    b.HasKey("AdminId");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("ECommerceBackEnd.Models.Adres", b =>
                {
                    b.Property<int>("AdresId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdresId"));

                    b.Property<string>("AcikAdres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdresId");

                    b.HasIndex("MusteriId");

                    b.ToTable("Adresler");
                });

            modelBuilder.Entity("ECommerceBackEnd.Models.Kategori", b =>
                {
                    b.Property<int>("KategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriID"));

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.HasKey("KategoriID");

                    b.ToTable("kategoris");
                });

            modelBuilder.Entity("ECommerceBackEnd.Models.KayitliKart", b =>
                {
                    b.Property<int>("KartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KartId"));

                    b.Property<string>("KartIsmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KartNumarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KartSahibi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<string>("SonKullanmaAy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SonKullanmaYil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KartId");

                    b.HasIndex("MusteriId");

                    b.ToTable("KayitliKartlar");
                });

            modelBuilder.Entity("ECommerceBackEnd.Models.Musteri", b =>
                {
                    b.Property<int>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriId"));

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("MusteriAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("MusteriMail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("MusteriSehir")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("MusteriSifre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("MusteriSoyadi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("MusteriTelNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR");

                    b.HasKey("MusteriId");

                    b.ToTable("musteris");
                });

            modelBuilder.Entity("ECommerceBackEnd.Models.Satislar", b =>
                {
                    b.Property<int>("SatislarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SatislarId"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int>("SiparisDurumu")
                        .HasColumnType("int");

                    b.Property<string>("SiparisNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TeslimatAdresiId")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("SatislarId");

                    b.HasIndex("MusteriId");

                    b.HasIndex("TeslimatAdresiId");

                    b.HasIndex("UrunId");

                    b.ToTable("satislars");
                });

            modelBuilder.Entity("ECommerceBackEnd.Models.Urun", b =>
                {
                    b.Property<int>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrunId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<decimal?>("IndirimliFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KategoriID")
                        .HasColumnType("int");

                    b.Property<string>("UrunAdi")
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("UrunGorsel")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("UrunMarka")
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.Property<decimal>("UrunSatisFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<short>("UrunStok")
                        .HasColumnType("smallint");

                    b.Property<bool>("UrunStokDurum")
                        .HasColumnType("bit");

                    b.Property<string>("UrunYazar")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.HasKey("UrunId");

                    b.HasIndex("KategoriID");

                    b.ToTable("uruns");
                });

            modelBuilder.Entity("ECommerceBackEnd.Models.Adres", b =>
                {
                    b.HasOne("ECommerceBackEnd.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("ECommerceBackEnd.Models.KayitliKart", b =>
                {
                    b.HasOne("ECommerceBackEnd.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("ECommerceBackEnd.Models.Satislar", b =>
                {
                    b.HasOne("ECommerceBackEnd.Models.Musteri", "Musteri")
                        .WithMany("satislars")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceBackEnd.Models.Adres", "TeslimatAdresi")
                        .WithMany()
                        .HasForeignKey("TeslimatAdresiId");

                    b.HasOne("ECommerceBackEnd.Models.Urun", "Urun")
                        .WithMany("satislars")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("TeslimatAdresi");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("ECommerceBackEnd.Models.Urun", b =>
                {
                    b.HasOne("ECommerceBackEnd.Models.Kategori", "Kategori")
                        .WithMany("uruns")
                        .HasForeignKey("KategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("ECommerceBackEnd.Models.Kategori", b =>
                {
                    b.Navigation("uruns");
                });

            modelBuilder.Entity("ECommerceBackEnd.Models.Musteri", b =>
                {
                    b.Navigation("satislars");
                });

            modelBuilder.Entity("ECommerceBackEnd.Models.Urun", b =>
                {
                    b.Navigation("satislars");
                });
#pragma warning restore 612, 618
        }
    }
}
